[mypy]
python_executable = D:/GitHub/cgel/.venv/Scripts/python.exe

[mypy-yaml.*]
ignore_missing_imports = True

[mypy-tqdm.*]
ignore_missing_imports = True

[mypy-jsonschema.*]
ignore_missing_imports = True

[mypy-pandas.*]
ignore_missing_imports = True

[mypy-stanza.*]
ignore_missing_imports = True

[mypy-mammoth.*]
ignore_missing_imports = True

[mypy-depedit.*]
ignore_missing_imports = True

[mypy-udapi.*]
ignore_missing_imports = True

[mypy-nltk.*]
ignore_missing_imports = True

[mypy-pylatexenc.*]
ignore_missing_imports = True

[mypy-plotnine.*]
ignore_missing_imports = True

[mypy-mizani.*]
ignore_missing_imports = True
